import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "@/styles/global.css";

export const metadata: Metadata = {
  title: "Giovanni Aranda",
  description: "Generated by create next app",
};

const montserrat = Montserrat({
  subsets: ["latin"],
  variable: "--font-mont",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${montserrat.className}`}>
      <body className={`antialiased`}>{children}</body>
    </html>
  );
}
